vp/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from vart import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', views.HomePageView.as_view(), name='home'),
    # register nenaudojamas, vartotojus prie sistemos turi prideti administratorius
    # url(r'^accounts/register/$', views.SignUpView.as_view(), name='signup'),
    url(r'^accounts/login/$', views.LoginView.as_view(), name='login'),
    url(r'^accounts/logout/$', views.LogOutView.as_view(), name='logout'),
    url(r'^laikotarpis/$', views.laikotarpis, name='laikotarpis'),
]

# planas
urlpatterns += [
    url(r'^planas/$', views.PlanasView.as_view(), name='planas'),
    url(r'^planas/(?P<kodas>\d+)/$', views.PlanasUpdate.as_view(), name='planas_update'),
    url(r'^planas/delete/(?P<kodas>\d+)/$', views.planas_delete_confirm, name='planas_delete_confirm'),
    url(r'^planas/delete/del/(?P<kodas>\d+)/$', views.PlanasDelete.as_view(), name='planas_delete'),
    # url(r'^planas/delete/del/(?P<kodas>\d+)/$', views.PlanasDelete.as_view(), name='planas_delete'),
    # url(r'^planas/kodas_add$', views.PlanasAdd.as_view(), name='planas_add'),
    url(r'^planas/kodas_add$', views.PlanasAdd.as_view(), name='planas_add'),
]

# sutartis
urlpatterns += [
    url(r'^mano_sutartis/(?P<kodas>[0-9-]+)/$', views.sutartis_view, name='sutartis_view'),
    url(r'^mano_sutartis/update/(?P<id_pk>[0-9-]+)/$', views.SutartisUpdate.as_view(), name='sutartis_update'),
    url(r'^mano_sutartis/copy/(?P<id_pk>[0-9-]+)/$', views.sutartis_copy, name='sutartis_copy'),
    url(r'^mano_sutartis/delete/(?P<id_pk>[0-9-]+)/$', views.sutartis_delete_confirm, name='sutartis_delete_confirm'),
    url(r'^mano_sutartis/delete/del/(?P<id_pk>[0-9-]+)/$', views.SutartisDelete.as_view(), name='sutartis_delete'),
    url(r'^mano_sutartis/sutartis_add/(?P<kodas>[0-9-]+)/$', views.SutartisAdd.as_view(), name='sutartis_add'),
]

# saskaitos fakturos
urlpatterns += [
    url(r'^faktura/(?P<id_pk>[0-9-]+)/$', views.FakturaView.as_view(), name='faktura'),
    url(r'^faktura/add/(?P<id_pk>[0-9-]+)/$', views.FakturaAdd.as_view(), name='faktura_add'),
    url(r'^faktura/update/(?P<id_pk>[0-9-]+)/$', views.FakturaUpdate.as_view(), name='faktura_update'),
    url(r'^faktura/copy/(?P<id_pk>[0-9-]+)/$', views.FakturaUpdate.as_view(), name='faktura_copy'),
    url(r'^faktura/delete/(?P<id_pk>[0-9-]+)/$', views.faktura_delete_confirm, name='faktura_delete_confirm'),
    url(r'^faktura/delete/del/(?P<id_pk>[0-9-]+)/$', views.FakturaDelete.as_view(), name='faktura_delete'),
]

# ataskaitu isvedimas i pdf
urlpatterns += [
    url(r'^users_pdf/$', views.print_users, name='users_pdf'),
    url(r'^planas_pdf/$', views.print_planas, name='planas_pdf'),
    url(r'^ivykdymas_pdf/$', views.print_ivykdymas, name='ivykdymas_pdf'),
    url(r'^zurnalas_pdf/$', views.print_zurnalas, name='zurnalas_pdf'),

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

vart/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from model_utils.models import SoftDeletableModel


# Create your models here.

'''
class Vartotojai(models.Model):
    organizatorius = models.CharField(max_length=50, unique=True)
    pareigos = models.CharField(max_length=200)
    adminas = models.BooleanField(default=False)
    aktyvus = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Vartotojai"
        verbose_name_plural = "Vartotojai"

    def __str__(self):
        return self.organizatorius
'''


class Planas(SoftDeletableModel):
    """ Planas

    Paveldi klase SoftDeletableModel kartu su Manager'iu SoftDeletableManager.
    Reikalinga tam, kad netrintu jau ivesto plano is duombazes, kad reikalui esant
    ta plana butu galima atstatyti tam paciam ar kitam vartotoji.
    SoftDeletableModel netrina iraso, o tik ji pazymi is_deleted.
    """
    PDP = (
        ('paslauga', 'Paslauga'),
        ('darbas', 'Darbas'),
        ('preke', 'Prekė'))
    organizatorius = models.ForeignKey(
        User,
        to_field='username',
        on_delete=models.CASCADE
        )
    kodas = models.CharField(max_length=30, unique=True)
    preke = models.CharField(
        max_length=100,
        verbose_name='Prekė, paslauga, darbas',
        unique=True
        )
    islaidos = models.DecimalField(max_digits=9, decimal_places=2)
    paslauga_darbas_preke = models.CharField(
        max_length=8,
        default='preke',
        choices=PDP
        )

    # deafaultinis Manager'is, grazina visus irasus, tame tarpe ir "istrintus"
    include_deleted = models.Manager()

    class Meta:
        verbose_name = "Planas"
        verbose_name_plural = "Planas"
        ordering = ['kodas']

    def __str__(self):
        return self.kodas + ': ' + self.preke


class Sutartis(models.Model):
    kodas = models.ForeignKey(
        Planas, to_field='kodas',
        on_delete=models.CASCADE,
        verbose_name='Kodas'
        )
    '''
    preke_sut = models.ForeignKey(
        Planas,
        to_field='preke',
        on_delete=models.SET_NULL,
        related_name='preke_sut',
        verbose_name='Pavadinimas',
        null=True
        )
    '''
    data = models.DateField(default=date.today, verbose_name='Sutarties data')
    suma = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name='Planuojama Suma'
        )
    tiekejo_kodas = models.DecimalField(
        max_digits=20,
        decimal_places=0,
        verbose_name='Tiekėjo kodas'
        )
    tiekejas = models.CharField(max_length=100, verbose_name='Tiekėjas')
    pastaba = models.CharField(
        max_length=200,
        verbose_name='Pastaba',
        blank=True
        )
    zalias = models.BooleanField(
        default=False,
        verbose_name='Ar tai žalias pirkimas?'
        )

    class Meta:
        verbose_name = "Sutartis"
        verbose_name_plural = "Sutartis"

    def __str__(self):
        k = self.kodas.kodas
        return 'ID:' + str(self.id)\
               + ', KODAS: ' + self.kodas.kodas\
               + ', PREKE: ' + self.kodas.preke\
               + ', DATA: ' + self.data.strftime('%Y-%m-%d')\
               + ', TIEKEJAS: ' + self.tiekejas


class Sf(models.Model):
    sf = models.CharField(max_length=50, verbose_name='Sąskaitos faktūros Nr.')
    sutartisid = models.ForeignKey(Sutartis, on_delete=models.CASCADE)
    suma = models.DecimalField(
        max_digits=9,
        decimal_places=2,
        verbose_name='Sąsk. faktūros suma'
        )
    data = models.DateField(verbose_name='Sąsk. faktūros data')
    pavadinimas = models.CharField(max_length=255, verbose_name='Pirkimo objektas')

    def __str__(self):
        return 'SUTARTIS: ' + self.sutartisid.kodas.kodas + ': ' + self.sutartisid.kodas.preke\
               + ', S.F.: ' + self.sf\
               + ', PAVADINIMAS: ' + self.pavadinimas\
               + ', S.F. SUMA: ' + str(self.suma)\
               + ', SUTARTIES DATA/S.F. DATA: ' + str(self.sutartisid.data) + '/' + str(self.data)

    class Meta:
        verbose_name = "Sąskaitos faktūros"
        verbose_name_plural = "Sąskaitos faktūros"
        ordering = ['data']

vart/views/auth_view.py
from django.db.models import Sum, Count
from django.views import generic
from braces import views
from vart.forms import RegistrationForm, LoginForm
from vart.models import Planas, Sutartis
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from datetime import date


class HomePageView(generic.TemplateView):
    """ Pagrindinis (home) puslapis.

    TODO:
    Jame yra rodoma atskira informacija prisijungusiems ir
    neprisijungusiems vartotojams.

    """
    template_name = 'notlogged.html'

    def get_context_data(self, **kwargs):
        # turbut nereikalingas
        # context = super(HomePageView, self).get_context_data(**kwargs)
        user_name = self.request.user.username

        data_nuo = date(date.today().year, 1, 1)
        data_iki = date(date.today().year, date.today().month, date.today().day)

        # kodas = get_object_or_404(Planas, kodas=kodas)

        # gaunam visus vartotojui priklausancius VP plano kodus
        planas = Planas.objects.filter(organizatorius=user_name)

        # filtruojam ivestas sutartis pagal pradzios ir pabaigos data
        # sutartys = Sutartis.objects.filter(data__range=[data_nuo, data_iki])

        metai = date.today().year
        sutartys = Sutartis.objects.filter(data__year=metai)

        # dar prafiltruojam sutartis pagal prisijungusio vartotojo VP kodus (visus),
        # kad neimtu kitu vartotoju ivestu sutarciu
        sut_id = sutartys.filter(kodas__in=planas)

        # velniskai sudetinga uzklausa ):
        # is jos paimtus duomenis atvaizduoja pagrindiniam puslapyje "ivykdytu pirkimu apzvalgoje".
        # paimam pagal data ir prisijungusio vartotojo VP kodus isfiltruotas sutartis sut_id,
        # grupuojam jas pagal laukus:
        # Sutartys.kodas->Planas.preke,
        # Sutartys.kodas->Planas.kodas,
        # Sutartys.kodas->Planas.islaidos,
        # toliau pagal atbulini ForeignKey is Sutartys i Sf skaiciuojam
        # Sf.sf count, Sf.suma sum, ir dar suskaiciuojam procentus.
        # gaunam QuerySet, priskiriam prie "fakturos", ir siunciam i puslapi.
        fakturos = sut_id.values(
            'kodas__preke', 'kodas__kodas', 'kodas__islaidos').\
            annotate(
            sf_count=Count('sf__sf'),
            sf_sum=Sum('sf__suma'),
            proc=(Sum('sf__suma')/Sum('kodas__islaidos'))*100)

        context = {
            'fakturos': fakturos,
            'username': self.request.user.username,
            'data_nuo': data_nuo,
            'data_iki': data_iki,
            'laikotarpis': str(metai),
        }
        return context


class SignUpView(
        views.AnonymousRequiredMixin,
        views.FormValidMessageMixin,
        generic.CreateView):
    """ Registracija. Šiaip turi būti nenaudojama
    (naujus vartotojus priregistruoti ir suteikti jiems teises turi administratorius per admin panel)

    """
    form_valid_message = 'Tu sekmingai prisiregistravai!'
    form_class = RegistrationForm
    model = User
    template_name = 'accounts/signup.html'


class LoginView(
        views.AnonymousRequiredMixin,
        views.FormValidMessageMixin,
        generic.FormView):
    """ Prisijungimas prie svetaines.

    Vartotojai privalo tureti administratoriaus suteiktus prisijungimo duomenis.

    """

    form_valid_message = 'Tu sėkmingai prisijungei '
    form_class = LoginForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            self.form_valid_message += 'vartotojo ' + '"' + username + '"' + ' vardu.'
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class LogOutView(
        views.LoginRequiredMixin,
        views.MessageMixin,
        generic.RedirectView):
    """ Atsijungimas nuo svetaines.

    """
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        self.messages.success("Tu atsijungei. Norint peržiūrėti ar suvesti duomenis turi vėl prisijungti.")
        return super(LogOutView, self).get(request, *args, **kwargs)

vart/views/auth_views.py
from django.db.models import Sum, Count, Max
from django.views import generic
from braces import views
from vart.forms import RegistrationForm, LoginForm
from vart.models import Planas, Sutartis
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth import authenticate, login, logout
from datetime import date


class HomePageView(generic.TemplateView):
    """ Pagrindinis (home) puslapis.

    Jame yra rodoma atskira informacija prisijungusiems ir
    neprisijungusiems vartotojams.

    """
    template_name = 'notlogged.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        user_name = self.request.user.username

        data_nuo = date(date.today().year, 1, 1)
        data_iki = date(date.today().year, date.today().month, date.today().day)

        # kodas = get_object_or_404(Planas, kodas=kodas)

        # gaunam visus vartotojui priklausancius VP plano kodus
        planas = Planas.objects.filter(organizatorius=user_name)

        # filtruojam ivestas sutartis pagal pradzios ir pabaigos data
        # sutartys = Sutartis.objects.filter(data__range=[data_nuo, data_iki])

        metai = date.today().year
        sutartys = Sutartis.objects.filter(data__year=metai)

        # dar prafiltruojam sutartis pagal prisijungusio vartotojo VP kodus (visus),
        # kad neimtu kitu vartotoju ivestu sutarciu
        sut_id = sutartys.filter(kodas__in=planas)

        # velniskai sudetinga uzklausa ):
        # is jos paimtus duomenis atvaizduoja pagrindiniam puslapyje "ivykdytu pirkimu apzvalgoje".
        # paimam pagal data ir prisijungusio vartotojo VP kodus isfiltruotas sutartis sut_id,
        # grupuojam jas pagal laukus:
        # Sutartys.kodas->Planas.preke,
        # Sutartys.kodas->Planas.kodas,
        # Sutartys.kodas->Planas.islaidos,
        # toliau pagal atbulini ForeignKey is Sutartys i Sf skaiciuojam
        # Sf.sf count, Sf.suma sum, ir dar suskaiciuojam procentus.
        # gaunam QuerySet, priskiriam prie "fakturos", ir siunciam i puslapi.
        fakturos = sut_id.values(
            'kodas__preke', 'kodas__kodas', 'kodas__islaidos').\
            annotate(
            sf_count=Count('sf__sf'),
            sf_sum=Sum('sf__suma'),
            proc=(Sum('sf__suma')/Max('kodas__islaidos'))*100)

        context.update({
            'fakturos': fakturos,
            'username': self.request.user.username,
            'data_nuo': data_nuo,
            'data_iki': data_iki,
            'laikotarpis': str(metai),
        })
        return context


class SignUpView(
        views.AnonymousRequiredMixin,
        views.FormValidMessageMixin,
        generic.CreateView):
    """ Registracija. Šiaip turi būti nenaudojama
    (naujus vartotojus priregistruoti ir suteikti jiems teises turi administratorius per admin panel)

    """
    form_valid_message = 'Tu sekmingai prisiregistravai!'
    form_class = RegistrationForm
    model = User
    template_name = 'accounts/signup.html'


class LoginView(
        views.AnonymousRequiredMixin,
        views.FormValidMessageMixin,
        generic.FormView):
    """ Prisijungimas prie svetaines.

    Vartotojai privalo tureti administratoriaus suteiktus prisijungimo duomenis.

    """

    form_valid_message = 'Tu sėkmingai prisijungei '
    form_class = LoginForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)

        if user is not None and user.is_active:
            self.form_valid_message += 'vartotojo ' + '"' + username + '"' + ' vardu.'
            login(self.request, user)
            return super(LoginView, self).form_valid(form)
        else:
            return self.form_invalid(form)


class LogOutView(
        views.LoginRequiredMixin,
        views.MessageMixin,
        generic.RedirectView):
    """ Atsijungimas nuo svetaines.

    """
    url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):
        logout(request)
        self.messages.success("Tu atsijungei. Norint peržiūrėti ar suvesti duomenis turi vėl prisijungti.")
        return super(LogOutView, self).get(request, *args, **kwargs)

vart/templates/bootstrap_temp.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap Starter Template</title>

    <!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">
        <br><br><br>
        <h1>Bootstrap Starter Template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.
            <br> All you get is this text and a mostly barebones HTML document.</p>
    </div>
    <!-- /.container -->


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>

</html>

vart/templates/faktura_delete_confirm.html
{% extends '_layouts/base.html' %}
{% block content%}
<h3>
<div class="well"><br><h2><strong>Dėmesio!</strong></h2><br>
    Sąskaita faktūra Nr. <strong>{{ context.sf }}, data: {{ context.data }}, suma: {{ context.suma }}</strong>
    bus <strong>negrįžtamai</strong> pašalinta.<br>
    Ar tu tikrai nori ją pašalinti?</p></h3>
<form action="{% url 'faktura_delete' id_pk=context.id %}" method="post">{% csrf_token %}
    <input type="button" class="btn btn-primary btn-lg active" value="Nenoriu šalinti" onclick="window.history.back()" />
     Taip, tikrai noriu pašalinti  <input type="submit" class="btn btn-danger btn-xs" value="x" />

</form>

{% endblock content %}

vart/templates/notlogged.html
{% extends 'home.html' %}

{%  block notlogged %}
    <div>
        Tam, kad kažką čia nuveikti, tu turi prisijungti savo vardu ir slaptažodžiu.
        Vartotojus prie sistemos prideda administratorius.
    </div>

{% endblock  %}

vart/templates/planas_add.html
{% extends '_layouts/base.html' %}
{% block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

vart/templates/sf_form.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sutarties redagavimas | {{ block.super }}{% endblock %}

{% block headline %}<h4><b>Sąskaita faktūra</b></h4>{% endblock %}

{% block content %}
    <div><h4><span class="text-info">VP kodas: </span><span
            class="text-primary"><strong>{{ context.kodas }}</strong></span></h4></div>
    <div><h4><span class="text-info">Tiekėjas: </span><span
            class="text-primary"><strong>{{ context.tiekejas }}</strong></span></h4></div>
    <div><h4><span class="text-info">Sutarties data: </span><span
            class="text-primary"><strong>{{ context.data }}</strong></span></h4></div>
    <div><h4><span class="text-info">Sutarties suma: </span><span
            class="text-primary"><strong>{{ context.suma }}</strong></span></h4></div>
    {% crispy form %}

    {% comment %}
        Sekantis JQuery pataiso i forma ivesta data.
        T.y. data galima ivesti formatais: 20161231, 2016-12-31; 2016.12.31, 2016,12,31, 2016/12/31
    {% endcomment %}

    <script>
        $(document).ready(function () {
            $("#id_data").change(function () {
                var data = $("#id_data").val();
                if (data.length == 8) {
                    data = data.slice(0, 4) + "-" + data.slice(4, 6) + "-" + data.slice(6, 8);
                }
                else {
                    data = data.split(/[.,\/ -]/);
                    data = data[0] + "-" + data[1] + "-" + data[2];
                }
                $("#id_data").val(data);
            });
        });

    </script>

{% endblock %}

vart/templates/sutartis_form.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sutarties redagavimas | {{ block.super }}{% endblock %}

{% block headline %}<h3><b>Įvesk kažką 1</b></h3>{% endblock %}

{% block content %}
    <div><h4><span class="text-info">VP kodas: </span><span class="text-primary"><strong>{{ kodas }}</strong></span></h4></div><br>
    {% crispy form %}

    {% comment %}
        Sekantis JQuery pataiso i forma ivesta data.
        T.y. data galima ivesti formatais: 20161231, 2016-12-31; 2016.12.31, 2016,12,31, 2016/12/31
    {% endcomment %}

    <script>
        $(document).ready(function () {
            $("#id_data").change(function () {
                var data = $("#id_data").val();
                if (data.length == 8) {
                    data = data.slice(0,4) + "-" + data.slice(4,6) + "-" + data.slice(6,8);
                }
                else {
                    data = data.split(/[.,\/ -]/);
                    data = data[0] + "-" + data[1] + "-" + data[2];
                }
                $("#id_data").val(data);
            });
        });

{% comment %}
 Funkcija autopaieskai formos lauke "tiekejas"
{% endcomment %}


$( function() {
    var availableSutartis = [
      {% for sut in visi_tiekejai %}
          '{{ sut|safe }}',
      {%endfor%}
    ];
    // alert(availableSutartis);
    $( "#id_tiekejas" ).autocomplete({
      source: availableSutartis
    });
  } );
</script>

{% endblock %}

vart/templates/sutartis_form_TRINTI.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title %}Sutarties redagavimas | {{ block.super }}{% endblock %}

{% block headline %}<h3><b>Įvesk kažką 1</b></h3>{% endblock %}

{% block content %}
    <div><h4><span class="text-info">VP kodas: </span><span class="text-primary"><strong>{{ kodas }}</strong></span></h4></div><br>
    {% crispy form %}

    {% comment %}
        Sekantis JQuery pataiso i forma ivesta data.
        T.y. data galima ivesti formatais: 20161231, 2016-12-31; 2016.12.31, 2016,12,31, 2016/12/31
    {% endcomment %}

    <script>
        $(document).ready(function () {
            $("#id_data").change(function () {
                var data = $("#id_data").val();
                if (data.length == 8) {
                    data = data.slice(0,4) + "-" + data.slice(4,6) + "-" + data.slice(6,8);
                }
                else {
                    data = data.split(/[.,\/ -]/);
                    data = data[0] + "-" + data[1] + "-" + data[2];
                }
                $("#id_data").val(data);
            });
        });

{% comment %}
 Funkcija autopaieskai formos lauke "tiekejas"
{% endcomment %}

$( function() {
    var availableSutartis = [
      {% for sut in visi_tiekejai %}
          '{{ sut|safe }}',
      {%endfor%}
    ];
    // alert(availableSutartis);
    $( "#id_tiekejas" ).autocomplete({
      source: availableSutartis
    });
  } );
</script>

{% endblock %}

vart/templates/update_form.html
{% extends '_layouts/base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{ formos_pavadinimas }} | {{ block.super }}{% endblock %}

{% block headline %}<h3><strong>{{ formos_pavadinimas }}</strong></h3>{% endblock %}

{% block content %}
    {% for infokey, infoval in papildoma_info.items %}
    <div><h4><span class="text-info">{{ infokey }}: </span><span class="text-primary"><strong>{{ infoval }}</strong></span></h4></div>
    {% endfor %}
    {% crispy form %}

    {% comment %}
        Sekantis JQuery pataiso i forma ivesta data.
        T.y. data galima ivesti formatais: 20161231, 2016-12-31; 2016.12.31, 2016,12,31, 2016/12/31
    {% endcomment %}

    <script>
        $(document).ready(function () {
            $("#id_data").change(function () {
                var data = $("#id_data").val();
                if (data.length == 8) {
                    data = data.slice(0,4) + "-" + data.slice(4,6) + "-" + data.slice(6,8);
                }
                else {
                    data = data.split(/[.,\/ -]/);
                    data = data[0] + "-" + data[1] + "-" + data[2];
                }
                $("#id_data").val(data);
            });
        });

{% comment %}
 Funkcija autopaieskai formos lauke "tiekejas"
{% endcomment %}

$( function() {
    var availableSutartis = [
      {% for sut in visi_tiekejai %}
          '{{ sut|safe }}',
      {%endfor%}
    ];
    // alert(availableSutartis);
    $( "#id_tiekejas" ).autocomplete({
      source: availableSutartis
    });
  } );
</script>

{% endblock %}